---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: ingress-whoami
spec:
  rules:
  - host: whoami.192.168.99.103.nip.io # TODO: Node IP setzen --> "kubectl get nodes -o wide"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port: 
              number: 80