---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: wordpress

spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
  selector:
    app: wordpress

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: default
data:
  WORDPRESS_DB_HOST: mariadb
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: default
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: d29yZHByZXNzX3Bhc3N3b3Jk

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: wordpress
  labels:
    app: wordpress

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:5.7.2
          envFrom:
            - configMapRef:
                name: wordpress-config
          env:
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: WORDPRESS_DB_PASSWORD
          volumeMounts:
            - mountPath: /var/www/html
              name: data
          ports:
            - name: http
              containerPort: 80
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wordpress-pvc
